// automatically generated by the FlatBuffers compiler, do not modify

package sample

const (
	PlayersNONE = 0
	PlayersPlayer = 1
)

var EnumNamesPlayers = map[int]string{
	PlayersNONE:"NONE",
	PlayersPlayer:"Player",
}

